# Generated by Django 5.0.6 on 2024-05-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_account_app", "0002_userbillinginformation_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="unique_referral_link",
            field=models.URLField(null=True),
        ),
    ]
