# Generated by Django 5.0.6 on 2024-05-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_account_app", "0003_userprofile_unique_referral_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="unique_referral_link",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
