# Generated by Django 5.0.6 on 2024-05-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Bitcoin", "Bitcoin"), ("Ethereum", "Ethereum")],
                        max_length=50,
                    ),
                ),
                ("image", models.ImageField(upload_to="coin_image/")),
                ("code", models.CharField(max_length=300)),
            ],
        ),
    ]
